# Generated by Django 2.2.5 on 2019-09-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neuron',
            fields=[
                ('neuron_id', models.IntegerField(primary_key=True, serialize=False)),
                ('neuron_name', models.CharField(max_length=100)),
                ('archive', models.CharField(max_length=100)),
                ('age_scale', models.CharField(max_length=100)),
                ('age_classification', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('strain', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('slicing_direction', models.CharField(max_length=100)),
                ('reconstruction_software', models.CharField(max_length=100)),
                ('objective_type', models.CharField(max_length=100)),
                ('original_format', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('attributes', models.CharField(max_length=100)),
                ('magnification', models.CharField(max_length=100)),
                ('shrinkage_reported', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('stain', models.CharField(max_length=100)),
                ('shrinkage_corrected', models.CharField(max_length=100)),
                ('physical_Integrity', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('upload_date', models.DateField()),
                ('deposition_date', models.DateField()),
                ('reported_value', models.FloatField()),
                ('reported_xy', models.FloatField()),
                ('reported_z', models.FloatField()),
                ('corrected_value', models.FloatField()),
                ('DecimalFieldcorrected_xy', models.FloatField()),
                ('corrected_z', models.FloatField()),
                ('soma_surface', models.FloatField()),
                ('surface', models.FloatField()),
                ('volume', models.FloatField()),
                ('slicing_thickness', models.FloatField()),
                ('min_age', models.FloatField()),
                ('max_age', models.FloatField()),
                ('min_weight', models.FloatField()),
                ('max_weight', models.FloatField()),
                ('png_url', models.URLField()),
            ],
        ),
    ]
