# Generated by Django 3.1.5 on 2021-01-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuron',
            name='reported_value',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
