# Generated by Django 3.1.5 on 2021-01-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210106_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuron',
            name='reported_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='reported_xy',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='reported_z',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
