# Generated by Django 3.1.5 on 2021-01-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210106_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuron',
            name='DecimalFieldcorrected_xy',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='corrected_value',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='corrected_z',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='max_age',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='max_weight',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='min_age',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='min_weight',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='slicing_thickness',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='soma_surface',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='surface',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='volume',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
