# Generated by Django 3.1.5 on 2021-01-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210106_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuron',
            name='shrinkage_corrected',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
